#### Seeds and determinism

We need our work to be reproducable, particularly with how a model was trained.

In [7]:
# Importing packages
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split

In [5]:
os.getcwd()

'/home/davidjeon/side_quests/ml_ops/day1/Session_1'

In [8]:
df = pd.read_csv("iris.csv")
df

     septal_length  sepal_width  petal_length  petal_width           class
0              5.1          3.5           1.4          0.2     Iris-setosa
1              4.9          3.0           1.4          0.2     Iris-setosa
2              4.7          3.2           1.3          0.2     Iris-setosa
3              4.6          3.1           1.5          0.2     Iris-setosa
4              5.0          3.6           1.4          0.2     Iris-setosa
..             ...          ...           ...          ...             ...
145            6.7          3.0           5.2          2.3  Iris-virginica
146            6.3          2.5           5.0          1.9  Iris-virginica
147            6.5          3.0           5.2          2.0  Iris-virginica
148            6.2          3.4           5.4          2.3  Iris-virginica
149            5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
# Let's shuffle the train/ test data split
X_train, X_test, y_train, y_test = train_test_split(df.drop('class', axis=1),df['class'], test_size=0.25, random_state=42)

In [10]:
X_train

     septal_length  sepal_width  petal_length  petal_width
4              5.0          3.6           1.4          0.2
32             5.2          4.1           1.5          0.1
142            5.8          2.7           5.1          1.9
85             6.0          3.4           4.5          1.6
86             6.7          3.1           4.7          1.5
..             ...          ...           ...          ...
71             6.1          2.8           4.0          1.3
106            4.9          2.5           4.5          1.7
14             5.8          4.0           1.2          0.2
92             5.8          2.6           4.0          1.2
102            7.1          3.0           5.9          2.1

[112 rows x 4 columns]

In [11]:
# Let's do another shuffle with a different random state
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(df.drop('class', axis=1),df['class'], test_size=0.25, random_state=7)
X_train_2

     septal_length  sepal_width  petal_length  petal_width
17             5.1          3.5           1.4          0.3
102            7.1          3.0           5.9          2.1
124            6.7          3.3           5.7          2.1
76             6.8          2.8           4.8          1.4
132            6.4          2.8           5.6          2.2
..             ...          ...           ...          ...
142            5.8          2.7           5.1          1.9
92             5.8          2.6           4.0          1.2
103            6.3          2.9           5.6          1.8
67             5.8          2.7           4.1          1.0
25             5.0          3.0           1.6          0.2

[112 rows x 4 columns]

In [12]:
diff = X_train.compare(X_train_2)
diff

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects

In [13]:
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(df.drop('class', axis=1),df['class'], test_size=0.25, random_state=42)
diff_2 = X_train.compare(X_train_3)
diff_2

Empty DataFrame
Columns: []
Index: []

### What's actually happening: pseudo-random number generators (PRNGs)

`random_state` **seeds a pseudo-random number generator (PRNG)** — an algorithm that produces a deterministic sequence of numbers that *looks* random but is fully reproducible given the same starting value.

The sequence is determined by an initial value -> Seed

- **Same seed → same sequence of numbers → same shuffle → same split.**  
  `random_state=42` always produces the same internal sequence, so `X_train` and `X_train_3` above are identical (empty diff).
- **Different seed → different sequence → different shuffle → different split.**  
  `random_state=7` starts from a different point in the sequence, so `X_train_2` differs from `X_train` (non-empty diff).

The PRNG itself is deterministic — there is nothing random about it. The "randomness" comes is that the deterministic ordering is close to a random approximation.

Leaving out the random_state and each run will be completely random and non-reproducible.

In [15]:
X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(df.drop('class', axis=1),df['class'], test_size=0.25)
X_train_5, X_test_5, y_train_5, y_test_5 = train_test_split(df.drop('class', axis=1),df['class'], test_size=0.25)
diff_3 = X_train_4.compare(X_train_5)

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects